-- 코드를 입력하세요
# SELECT ROUND(Avg(DAILY_FEE),0) as AVERAGE_FEE From CAR_RENTAL_COMPANY_CAR where CAR_TYPE = "SUV"

SELECT ROUND(Avg(DAILY_FEE),0) as AVERAGE_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = "SUV"