-- 코드를 입력하세요
# SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH FROM MEMBER_PROFILE WHERE SUBSTRING(DATE_OF_BIRTH,6,2)='03'AND GENDER='W' AND LENGTH(TLNO)>0 ORDER BY MEMBER_ID

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") as DATE_OF_BIRTH FROM MEMBER_PROFILE WHERE MONTH(DATE_OF_BIRTH) = "3" and GENDER = "W" and LENGTH(TLNO)>0 ORDER BY MEMBER_ID